muzisystem/urls.py
from django.conf.urls import url
from . import views
app_name = 'muzisystem'


urlpatterns = [
    # for /index/
    url(r'^uploadtracks/$', views.upload_track, name='utracks'),
    url(r'^uploadalbums/$', views.upload_album, name='ualbums'),
    url(r'^home/$', views.home, name='home'),
    url(r'^uploadgenre/$', views.upload_genre, name='ugenre'),
    url(r'^uploadartist/$', views.upload_artist, name='uartist'),
 ]

mymuzi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('muzisystem.urls', namespace='mymuzi', app_name='mymuzi')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

muzisystem/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import date


def url_track_thumbnail(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(instance.track_name, ext)
    return "{id}/thumbnails/{file}".format(id=instance.album_id.album_name, file=filename)


def url_track(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(instance.track_name, ext)
    return "{id}/{file}".format(id=instance.album_id.album_name, file=filename)


def url_album_thumbnail(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(instance.album_name, ext)
    return "{id}/thumbnails/{file}".format(id=instance.album_name, file=filename)


def url_artist(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(instance.artist_name, ext)
    return "artists/{file}".format(file=filename)


class Artists(models.Model):
    artist_name = models.CharField(max_length=250)
    artist_description = models.CharField(max_length=1000)
    artist_picture = models.ImageField(upload_to=url_artist)

    def __str__(self):
        return self.artist_name


class Genre(models.Model):
    genre_name = models.CharField(max_length=250)
    genre_description = models.CharField(max_length=1000)

    def __str__(self):
        return self.genre_name


class Albums(models.Model):
    artist_id = models.ForeignKey('Artists', on_delete=models.CASCADE)
    album_name = models.CharField(max_length=250)
    album_releasedate = models.DateField(default=date.today)
    genre_id = models.ForeignKey('Genre')
    album_thumbnail = models.FileField(upload_to=url_album_thumbnail)

    def __str__(self):
        return self.album_name + ' ( ' + self.artist_id.artist_name + ' ) '


class Tracks(models.Model):
    album_id = models.ForeignKey('Albums', on_delete=models.CASCADE)
    track_name = models.CharField(max_length=250)
    track_thumbnail = models.ImageField(upload_to=url_track_thumbnail, blank=True)
    track = models.FileField(upload_to=url_track)

    def __str__(self):
        return self.track_name + ' ( ' + self.album_id.album_name + ' ) '

muzisystem/forms.py
from django import forms
from .models import *


class TrackForm(forms.ModelForm):
    class Meta:
        model = Tracks
        fields = ('album_id', 'track_name', 'track_thumbnail', 'track',)


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Albums
        fields = ('artist_id', 'album_name', 'album_releasedate', 'genre_id', 'album_thumbnail',)


class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artists
        fields = ('artist_name', 'artist_description', 'artist_picture',)


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ('genre_name', 'genre_description',)

muzisystem/views.py
from django.shortcuts import render, redirect
from .models import Albums, Tracks
from .forms import *


def home(request):
    return render(request, 'testing.html', {'Albums': Albums.objects.all(), 'Tracks': Tracks.objects.all()})

def upload_track(request):
    if request.method == 'POST':
        form = TrackForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('muzisystem:home')
    else:
        form = TrackForm()
    return render(request, 'model_form_upload.html', {
        'form': form})

def upload_album(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('muzisystem:home')
    else:
        form = AlbumForm()
    return render(request, 'model_form_upload.html', {'form': form})

def upload_genre(request):
    if request.method == 'POST':
        form = GenreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('muzisystem:home')
    else:
        form = GenreForm()
    return render(request, 'model_form_upload.html', {'form': form})

def upload_artist(request):
    if request.method == 'POST':
        form = ArtistForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('muzisystem:home')
    else:
        form = ArtistForm()
    return render(request, 'model_form_upload.html', {'form': form})

muzisystem/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Simple File Upload</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

muzisystem/templates/model_form_upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'muzisystem:home' %}">Return to home</a></p>
{% endblock %}

muzisystem/templates/testing.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for album in Albums %}
        <a href="{{ album.album_thumbnail.url }}"> {{ album.album_name }} (Genre: {{ album.genre_id.genre_name }}) Artist:{{ album.artist_id.artist_name }} </a>
        <ui>
        <br>
            Songs Given Below
            {% for track in Tracks %}
                {% if track.album_id == album %}
                    <li>
                        <a href="{{ track.track.url }}"> {{ track.track_name }}&nbsp;</a>
                        {% if track.track_thumbnail == '' %}
                        <a href="{{ album.album_thumbnail.url }}"> (Thumbnail) </a>

                        {% else %}
                        <a href="{{ track.track_thumbnail.url }}"> (Thumbnail) </a>
                        {% endif %}
                    </li>
                {% endif %}
            {% endfor %}
        </ui>
        <br>
    {% endfor %}

    <br>
    <h4>Upload from Here</h4>
    <a href={% url 'mymuzi:utracks' %}> Upload Tracks </a>
    <br>
    <a href={% url 'mymuzi:ualbums' %}> Upload Albums </a>
    <br>
    <a href={% url 'mymuzi:uartist' %}> Upload Artists </a>
    <br>
    <a href={% url 'mymuzi:ugenre' %}> Upload Genre </a>
</body>
</html>